### ISSUE TITLE
some events not appearing in Google Calendar

### ISSUE THREAD

**Issue by aspiers** [vuntz/maildir-to-ics#8]
E.g. most of my daily standup appointments are not appearing via the feed Google Calendar receives from my automated `maildir-to-ics` run.  Not sure why yet, but this issue is a placeholder for tracking it.

**Comment by vuntz** [comment]
@aspiers would be interesting to know if you still see this with the latest code. I suspect some of that might have been related to the broken hacks we had and that got removed.

**Comment by aspiers** [comment]
I've just updated the code to `master`, so let's see how it goes.  Gotta wait for Google Calendar to do a refresh before I'm able to compare with Groupwise calendar ...

**Comment by aspiers** [comment]
Submitted some more fixes which should help with this, in particular I suspect #13 is likely to have prematurely truncated the .ics file.

**Comment by aspiers** [comment]
Fairly confident this is fixed by #13 so closing now.  Will reopen if I spot it again.
